sudo: enabled

language: minimal

addons:
    apt:
        packages:
            - docker-ce

script:
    - ./bin/deploy.sh

deploy:
    provider: s3
    access_key_id: $AWS_S3_KEY_ID
    secret_access_key: $AWS_S3_ACCESS_KEY
    bucket: $AWS_S3_BUCKET
    local_dir: blog/_site
    skip_cleanup: true
    detect_encoding: true

notifications:
    email: false
